### ISSUE TITLE
Disabling Tiling on widget menus and pope ups!

### ISSUE THREAD

**Issue by mmrezaie** [faho/kwin-tiling#100]
When I open some menu-like interfaces like application launcher's menu (Sorry I do not know what they are, menu? widget? window? but they all have a frame), Kwin treats them as a window, so they get tiled, which breaks some of these widgets.

Can I change this behavior or this is by design or something which Kwim won't differentiate?

p.s. I wanna clarify that this doesn't happen for all the widgets and drop down menus for skype, or Dropbox or chrome are fine. But for others mostly the ones integrated with KDE-plasma they are usually are the ones being tiled.

**Comment by faho** [comment]
What the script does is ignore all clients that aren't normal windows. This goes via the X11 window "type".

If an application's menus are tiled, then that means that that application (or its toolkit) doesn't correctly flag them, which is a bug there.

>he ones integrated with KDE-plasma

The ones integrated with KDE-plasma are already hardcoded to be ignored.

Do you use latte-dock? That apparently doesn't do this correctly - see #97.

**Comment by mmrezaie** [comment]
Genius! Yes, I do use Latte. I should have mentioned it.

**Comment by faho** [comment]
>Yes, I do use Latte.

In that case, you'll need to do what I recommended in #97 and ignore "lattedock" in the settings.

**Comment by mmrezaie** [comment]
thanks, I already did it. I will close this thread since the other one (#97) is older, and more into the point. Thank you very much.
