### ISSUE TITLE
Shortcuts not working

### ISSUE THREAD

**Issue by elpaso** [faho/kwin-tiling#102]
Hi, sorry if this is more a question than an issues, but Meta (Windows) + PgUP/Down and Meta+F does nothing on my system (ubuntu xenial), I've gone through the system settings keyboard shortcut configuration without success, what can I check?

**Comment by TiGR** [comment]
You need to go to Window Manager settings > Kwin scripts and enable Tiling script there.

**Comment by faho** [comment]
Sorry I missed this!

I'm assuming you've either lost interest or solved it, so I'm closing.

Please feel free to comment so we'll reopen!
