### ISSUE TITLE
Question Window Title

### ISSUE THREAD

**Issue by ejabu** [faho/kwin-tiling#108]
I have a question which is unrelated to the script functionality

![image](https://github.com/faho/faho.github.io/raw/master/img/kwin-tiling02.png)

According to picture that you provided, your window title seems align to the left. How did you do it?

As I am new to KDE environment and trying to modify my own plasma screen, is it possible to create Kwin Scripts like this repo to modify any App Bar Alignment ? 

Or do I need to make another other than scripts, e.g theme, look-and-feel ?

I am really appreciated if you willing to discuss here. As I could not find any forums to kde modification

**Comment by faho** [comment]
As far as I know, it's just from an old KDE version. I can't find any way to get it that way now.

I don't tend to use titlebars at all, actually.

>As I am new to KDE environment and trying to modify my own plasma screen, is it possible to create Kwin Scripts like this repo to modify any App Bar Alignment ?

Check [the KWIN API docs](https://techbase.kde.org/Development/Tutorials/KWin/Scripting/API_4.9). I can't find anything related to the title bar there, except a way to hide/show it.

So I'd imagine that, yes, you'd have to make a theme, if it's at all possible.

>As I could not find any forums to kde modification

Try https://forum.kde.org/.
