### ISSUE TITLE
Some windows misbehave

### ISSUE THREAD

**Issue by wd5gnr** [faho/kwin-tiling#110]
This could be my configuration but:

gtkwave -- when started, almost always vanishes. You have to cause it to jump to another tile for it to work. In some cases, the window is visible but non responsive until you move it a temp position.

Wine (at least MS Office running under Wine) doesn't obey at all. It floats over everything. 

Love this script, by the way. Those two things are minor.

**Comment by faho** [comment]
>gtkwave -- when started, almost always vanishes. You have to cause it to jump to another tile for it to work. In some cases, the window is visible but non responsive until you move it a temp position.

#6.

>Wine (at least MS Office running under Wine) doesn't obey at all. It floats over everything.

Wine applications are [hardcoded to tile](https://github.com/faho/kwin-tiling/blob/master/contents/code/tilelist.js#L67). That's because they're not in any way prepared to tile, so it just won't work.

**Comment by wd5gnr** [comment]
Thanks. I just looked at the source and saw the Wine hardcoding. I'll look at #6.
