### ISSUE TITLE
Tiling suddenly stopped working

### ISSUE THREAD

**Issue by roadriverrail** [faho/kwin-tiling#112]
After an upgrade to Ubuntu 18.04.1 (I run Plasma on Ubuntu), the kwin-tiling script stopped tiling windows.  I've had some minor issues in the past, but this is just not tiling anything ever as far as I can tell.  I've tried removing and reinstalling it using plasmapkg2, but nothing seems to be working.  I'm not very familiar with kwin scripts so I can't even be sure how to get you some logging to look at.

**Comment by faho** [comment]
You'll want to make sure with kdebugsettings and kdebugdialog (for some reason there's two, I dunno) that kwin's debug output is turned on, and then you'll want to launch

```
kwin_x11 --replace
```

in a console.

The script should print a bunch of debug messages, like 

```
qml: Starting tiling
```

**Comment by roadriverrail** [comment]
I installed kdebugsettings.  Running it, there weren't any options for kwin-tiling that I could see.  I skipped ahead to running `kwin_x11` and did see the logging line you mention.  The whole log is below.

When I ran this command, windows did re-tile, and it looked like moving tiled windows around did sort of preserve the tiling.  However, when I pulled a Chrome tab out into its own window, it did not retile.  Additionally, when I started a new Konsole, it just filled a screen rather than respecting the tiling.  Again, this all worked just find not-that-long-ago.

`rhett@downhome:~/kwin-tiling$ kwin_x11 --replace
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setWindow: Painter not active
QPainter::setClipRect: Painter not active
QPainter::save: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setClipRect: Painter not active
QPainter::drawRects: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::save: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::drawRects: Painter not active
QPainter::restore: Unbalanced save/restore
kwin_core: Compositing is not possible
qml: We're running under KWin 5
qml: We're running under KWin 5
qml: We're running under KWin 5
qml: We're running under KWin 5
qml: We're running under KWin 5
qml: Signal test 1: SUCCESS
qml: Signal test 2: SUCCESS
qml: Testing configuration
qml: Reading floaters
qml: We're running under KWin 5
qml: Starting tiling
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setWindow: Painter not active
QPainter::setClipRect: Painter not active
QPainter::save: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setClipRect: Painter not active
QPainter::drawRects: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::save: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::drawRects: Painter not active
QPainter::restore: Unbalanced save/restore
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 7735, resource id: 96469025, major code: 15 (QueryTree), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 8964, resource id: 31457418, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 15298, resource id: 27263005, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 15302, resource id: 31457419, major code: 18 (ChangeProperty), minor code: 0
`

**Comment by roadriverrail** [comment]
I notice a lot of these lines appearing when I create and/or destroy new windows.  I don't know if it's related...

```
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 4609, resource id: 115343376, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 5524, resource id: 31457421, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 5845, resource id: 115343813, major code: 15 (QueryTree), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 7445, resource id: 115344398, major code: 15 (QueryTree), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 7538, resource id: 31457422, major code: 18 (ChangeProperty), minor code: 0


qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 9960, resource id: 31457424, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 13813, resource id: 31457425, major code: 18 (ChangeProperty), minor code: 0
```

**Comment by faho** [comment]
That's just your basic log spam.

According to this, the script is active and running.

Are you sure you aren't running wayland (where the script currently can't work because kwin won't tell it about wayland clients), and that you haven't disabled tiling?

**Comment by roadriverrail** [comment]
Fairly sure it's x11:
```
rhett@downhome:~/kwin-tiling$ loginctl show-session c2 -p Type
Type=x11
```

When I go to the KWin Scripts panel, "Tiling Extension" is checked.  Under "Common options", "Tiling enabled by default" is also checked.  So is "Respect minimum/maximum Size"; don't know if that matters.  Generally, at startup, I'll see a couple of windows tile themselves, then Konsole loads and it's actually not visible because it's layered under the tiled windows and I have to fiddle with it to make it visible.

It actually looks like, once the script engages, it provides a tiling of all active windows, but any new windows created aren't being tiled.

**Comment by faho** [comment]
> any new windows created aren't being tiled.

Is there any debug output when that happens?

**Comment by roadriverrail** [comment]
The "log spam" from a couple of messages back was all I was seeing on creation of new windows.  I've kept playing around with it.  When I make new windows, they appear to start out as floating windows.  They start tiling after I minimize them and maximize them.  There's nothing I can see in the logs when I minimize/maximize.

**Comment by faho** [comment]
Do you use the tiling script from git or from the "Get Scripts" menu (which goes via kde-look.org)?

**Comment by faho** [comment]
Okay, I've just made a "debug" branch with a few more prints. Please try that and upload the output!

Also please check if you are using compositing - unfortunately we need to add clients slightly differently depending on if compositing is active or not, and there doesn't seem to be a working way to get the _current_ compositing state, only how it was on startup. So if KWin for some reason decided to turn off compositing after starting, you'd see this.

**Comment by roadriverrail** [comment]
So, I pulled down what I could find about my compositing state:

```
Compositing
===========
Compositing is not active

rhett@downhome:~/$ qdbus org.kde.KWin /KWin supportInformation | grep ompos
Composite: yes; Version: 0x4
compositingMode: 1
useCompositing: true
compositingInitialized: false
windowsBlockCompositing: true
Compositing
Compositing is not active
rhett@downhome:~/$ qdbus org.kde.KWin /Compositor org.kde.kwin.Compositing.active
false
```

I have no idea if that helps at all; that reflects the current compositing state but not the one present when kwin was started.  On a lark, I went to check my compositor settings and OpenGL detection had been turned off due to a driver-related crash in the past, or so it said.  I re-enabled OpenGL detection and restarted kwin from the comandline and now...

```
rhett@downhome:~/$ qdbus org.kde.KWin /Compositor org.kde.kwin.Compositing.active
true
```

I kicked off another Konsole, and lo and behold, it tiled immediately.  I think I might play around with this for part of the day and see if works out.  It does play into your hypothesis...it's possible compositing started out being on but was disabled due to the OpenGL check being disabled, leading to that mixed state you mentioned.

**Comment by faho** [comment]
>I kicked off another Konsole, and lo and behold, it tiled immediately

Good to know!

>it's possible compositing started out being on but was disabled due to the OpenGL check being disabled

Probably. I just checked again, and while there's three different variables related to compositing, and three changed-signals, none of them actually work.

I'd file a KWin issue, but I'm pretty sure I did already, years ago, along with five other things.

So let's close this for now, if the problem reoccurs we can reopen!

**Comment by SimonSelg** [comment]
> So, I pulled down what I could find about my compositing state:
> 
> ```
> Compositing
> ===========
> Compositing is not active
> 
> rhett@downhome:~/$ qdbus org.kde.KWin /KWin supportInformation | grep ompos
> Composite: yes; Version: 0x4
> compositingMode: 1
> useCompositing: true
> compositingInitialized: false
> windowsBlockCompositing: true
> Compositing
> Compositing is not active
> rhett@downhome:~/$ qdbus org.kde.KWin /Compositor org.kde.kwin.Compositing.active
> false
> ```
> 
> I have no idea if that helps at all; that reflects the current compositing state but not the one present when kwin was started. On a lark, I went to check my compositor settings and OpenGL detection had been turned off due to a driver-related crash in the past, or so it said. I re-enabled OpenGL detection and restarted kwin from the comandline and now...
> 
> ```
> rhett@downhome:~/$ qdbus org.kde.KWin /Compositor org.kde.kwin.Compositing.active
> true
> ```
> 
> I kicked off another Konsole, and lo and behold, it tiled immediately. I think I might play around with this for part of the day and see if works out. It does play into your hypothesis...it's possible compositing started out being on but was disabled due to the OpenGL check being disabled, leading to that mixed state you mentioned.

Thank you for this. I was having the exact same problem, this fixed it for me. 

@faha: this could maybe linked in the faq/troubleshooting section?
