### ISSUE TITLE
Upper case classnames are not excluded

### ISSUE THREAD

**Issue by ilkerhk** [faho/kwin-tiling#118]
Hello,
Classnames containing uppercase letters can't be excluded. 

One workaround is following: If classname is SampleClass than one needs to enter sampleclass in order to exclude that. 
Maybe the classnames obtained from kwin are lowercased and then compared to exclude list?

**Comment by ilkerhk** [comment]
I see. Then, I think case insensitive matching would be better and not confusing. Because tools like xprop shows upper cases in the classnames.

**Comment by faho** [comment]
Done.
