### ISSUE TITLE
Resizing more than 1 axis

### ISSUE THREAD

**Issue by apgrc** [faho/kwin-tiling#119]
When I have 3 windows opened on a configuration like this

![image](https://user-images.githubusercontent.com/43510217/50268118-61cda180-03de-11e9-8cac-6bbdca9b34f6.png)

and resize vertically one of the windows on the right they also get smaller horizontally.
And if I resize them horizontally, the active windows gets smaller vertically.

**Comment by faho** [comment]
Duplicate of #111
