### ISSUE TITLE
Enhancement: Notification about state changes

### ISSUE THREAD

**Issue by gerion0** [faho/kwin-tiling#127]
It would be nice, especially for beginners, if there would be some indication in which state the script/kwin is. With state I mean variables like: Is tiling active, what tiling mode is active.

This could be a tray icon, or a notification when you switch state or both (similar to the volume controls).

**Comment by faho** [comment]
I don't think that's possible using the kwin scripting API. Technically we could make arbitrary dbus calls, but that would then require running a daemon alongside it.

It should also technically be possible to draw stuff using QML, but I've never gotten that to work.

So: Sorry, probably not going to happen.
