### ISSUE TITLE
Keyboard shortcuts "Move Window Up" and "Move Window Left" don't work...

### ISSUE THREAD

**Issue by ithez** [faho/kwin-tiling#33]
This is a great script, thank you much for creating it! Exactly what I have been wanting!

My only issue is that the keyboard shortcuts for "Move Window Up" and "Move Window Left" don't work. I'm still a noob with linux, so not sure if I did something wrong; but I would really appreciate any help to get these shortcuts working. Thanks!

**Comment by faho** [comment]
So since I always wanted to give Fedora a spin I have now set up a VM running KDE SC4, in which I have just committed 1c976f02cbfc7903e776dc8e878f1a8bef8d3fe0 (as a fixup to the commit before it), which takes gaps into account when getting a tile by position.

If that was your issue, it is now fixed.

If not, please reopen this or open another one.

**Comment by fbob** [comment]
My  keyboard shortcuts for "Move Window ..."  don't work. I bind them to meta+maj+arrow keys ...

I'm using  kde 4.13.3 on kubuntu 14.04 with current git version of the kwin-tiling script.

I would really appreciate any help to get these shortcuts working. 
Thank you very much !

**Comment by faho** [comment]
Does it fail regardless of what key you bind it to? Does the script work otherwise?

**Comment by fbob** [comment]
It looks like so, I've just changed the key bindings and got the same effect: nothing move.
By the way the others kwin-tiling script features are working wonderfully  :) Thanks !

**Comment by faho** [comment]
Hmmm... I'm going to need some debug information. The first thing you could do is to upload your ~/.xsession-errors (and you can scrub anything personal or obviously not KWin related, but please don't be too eager). If that doesn't yield any errors, then we'd have to add some debug prints (yeah, I know).

In `~/.kde4/share/apps/kwin/scripts/kwin-script-tiling/contents/code/tilingmanager.js` (open with a text editor) in _moveTile (line 699 on my copy, though I'm not sure I've commited all P4 stuff), right before `if (direction == Direction.Left) {` (line 708), could you add the following:

    print("TilingManager._moveTile", client);
    print(client.resourceClass.toString(), direction);

then start `kwin --replace` in a terminal, try to move a tile and upload the output?

**Comment by fbob** [comment]
Here is the ~/.xsession-errors:

     Script for ibus started at run_im.
     Script for auto started at run_im.
     Script for default started at run_im.

After the modification of `tilingmanager.js ` a  `kwin --replace` gives me:

    % kwin --replace
    QDBusConnection: session D-Bus connection created before QCoreApplication. Application may  misbehave.
    QCoreApplication::sendPostedEvents: Cannot send posted events for objects in another thread
    QCoreApplication::sendPostedEvents: Cannot send posted events for objects in another thread
    QCoreApplication::sendPostedEvents: Cannot send posted events for objects in another thread
    QCoreApplication::sendPostedEvents: Cannot send posted events for objects in another thread
    Signal test 1: SUCCESS
    Signal test 2: SUCCESS
    Testing configuration
    Reading floaters
    Read floaters
    Configuration option floaters :  latexdraw,yakuake,plasma,plasma-desktop,krunner,plugin-container,klipper,Wine
    Starting tiling
    Creating HalfLayout
    Creating HalfLayout

And when I try to move a window to the left with my keyboard shortcut, I get:

    TilingManager._moveTile KWin::Client(name = "")
    systemsettings 2

Hope this help :)
