### ISSUE TITLE
prepend KWIN-TILING: to keyboard shortcuts 

### ISSUE THREAD

**Issue by Konfekt** [faho/kwin-tiling#38]
This way, it is clearer which shortcuts are active if and only if kwin-tiling is active.

**Comment by faho** [comment]
I've thought about that, if I recall correctly the problem was that upgraded installations would retain stale entries, which I find much more confusing.

**Comment by Konfekt** [comment]
Well, confusing is also that uninstalled installations retain stale entries.

**Comment by faho** [comment]
The script API doesn't offer that functionality. The closest thing I know of is a button in the shortcuts config menu that offers to delete _all_ kwin shortcuts - those that are still used will then be recreated on the next start.

I'm afraid if you want this properly we need support from upstream, I'm unconvinced that adding a prefix is good enough to warrant leaving stale duplicate entries.

**Comment by Konfekt** [comment]
Ok, we can wait for kwin upstream. Still, even duplicate prefixed entires help identifyng those stale ones from prior kwin-tiling installations.

**Comment by faho** [comment]
As a reminder to myself: I need to actually check what the "title" and "text" arguments to registerShortcut() actually are. If the "text" is what is presented then we could just change that and at least make users who go through the kcm completely happy. Those who fiddle with kglobalshortcutsrc would need to look at the descriptions.

**Comment by faho** [comment]
This is done in git for the plasma 5 version, it just won't be released until the shortcuts actually _work_ again.
