### ISSUE TITLE
Kubuntu 15.04/Plasma 5 issue

### ISSUE THREAD

**Issue by fbob** [faho/kwin-tiling#39]
It looks like the tiling extension available for download in Window management > Kwin scripts  does not work with Kubuntu 15.04/Plasma 5.

**Comment by faho** [comment]
Yep, I know. The "plasma5" branch of this very git repo does work, with some issues, the most annoying of which is that shortcuts don't work.

Until that's solved in kwin5 or until I can somehow mark a script as compatible to a certain kwin version the one in GHNS will remain the one for kwin4. If you want to use it now, install from git (git clone, `plasmapkg2 -t kwinscript -i /path/to/git/repo`).

**Comment by fbob** [comment]
Great thank you very much faho for this precisions. 
I will try the git version. 

Thank you again for this awesome piece of work: kwin tiling just rocks ! 

Francois 


François BEAUBERT 
Maître de Conférences 
LAMIH CNRS UMR 8201 – Département de Mécanique 
ENSIAME - Université de Valenciennes et du Hainaut-Cambrésis 
Le Mont Houy 
59313 Valenciennes CEDEX 9 
Tél : 03 27 51 19 80 
Fax : 03 27 51 19 61 
E-mail : francois.beaubert@univ-valenciennes.fr 


----- Mail original -----

De: "faho" <notifications@github.com> 
À: "faho/kwin-tiling" <kwin-tiling@noreply.github.com> 
Cc: "François Beaubert" <francois.beaubert@univ-valenciennes.fr> 
Envoyé: Lundi 27 Avril 2015 00:28:31 
Objet: {Disarmed} Re: [kwin-tiling] Kubuntu 15.04/Plasma 5 issue (#39) 



Yep, I know. The "plasma5" branch of this very git repo does work, with some issues, the most annoying of which is that shortcuts don't work. 

Until that's solved in kwin5 or until I can somehow mark a script as compatible to a certain kwin version the one in GHNS will remain the one for kwin4. If you want to use it now, install from git (git clone, plasmapkg2 -t kwinscript -i /path/to/git/repo ).
