### ISSUE TITLE
high dpi issues in config menu

### ISSUE THREAD

**Issue by jneureuther** [faho/kwin-tiling#40]
I have a high dpi screen (144dpi) and the config menu is quite messed up (see screenshots).
Maybe the ```qSizePolicy```[1] is the right way to fix this issue.

[1] http://doc.qt.io/qt-4.8/qsizepolicy.html

<img width="586" alt="dpi_issue2" src="https://cloud.githubusercontent.com/assets/4653434/8507937/d08e737a-2259-11e5-9f88-f580e1a67532.png">
<img width="586" alt="dpi_issue1" src="https://cloud.githubusercontent.com/assets/4653434/8507938/d9c6e01c-2259-11e5-8621-f05ba575a46f.png">

**Comment by faho** [comment]
The issue here is probably that we hardcode some coordinates in config.ui.

**Comment by faho** [comment]
1838f2f7afa75b0eb0861a7659378caa96e968d6 could help with this.

Please try that commit (or current master, they are equivalent) as I don't have a HiDPI machine to test.

**Comment by jneureuther** [comment]
@faho thanks for looking into this!
Tab1 now looks ok, Tab2 is unchanged (see screenshots)
<img width="575" alt="tiling1" src="https://cloud.githubusercontent.com/assets/4653434/8512457/b4a70312-2343-11e5-9e1e-13ebee835680.png">
<img width="575" alt="tiling2" src="https://cloud.githubusercontent.com/assets/4653434/8512458/b782a1c2-2343-11e5-9d72-4366ecb154e6.png">

**Comment by faho** [comment]
Please try bdef8b7089ec7751da01aa4f3ca902e2db0850fc - it should now adapt to window resizing, so it might work better on HiDPI too.

**Comment by jneureuther** [comment]
Now it looks fine:
<img width="799" alt="tiling4" src="https://cloud.githubusercontent.com/assets/4653434/8622981/e38e34cc-272e-11e5-875b-ee5089b5b192.png">

Thanks for the fix, in my opinion the issue can be closed now.
