### ISSUE TITLE
Can't install on Debian Testing

### ISSUE THREAD

**Issue by MaxG87** [faho/kwin-tiling#42]
Hi,
I am unable to install this script on Debian Testing. Following the description changes nothing besides that the folder is copied to somewhere else. Did you mean plasmapgk2 instead of plasmapkg?

I manually copied the folder to ~/.local/share/kservices5/ which made the 'Tiling Extension' turn up at Systemsteuerung -> Fensterverwaltung -> KWin-Scripte. It's German but since some here seem to be native German speakers I did not translate in order to avoid mistakes. However, when I try to open the settings it says *Das Modul liefert am erwarteten Speicherort keine Konfigurationsdatei.*

Do I do something wrong?

**Comment by faho** [comment]
>Did you mean plasmapgk2 instead of plasmapkg?

Yes, for Plasma 5 it's `plasmapkg2`. I ought to adjust the README to reflect that.

>It's German but since some here seem to be native German speakers I did not translate in order to avoid mistakes.

Das dürfte kein Problem sein :smile:.

>However, when I try to open the settings it says Das Modul liefert am erwarteten Speicherort keine Konfigurationsdatei.

Did you install the latest git version? That should have been fixed in fcc931cccf25cb2d9bef6c182a3a6dc503db4940.

If you did, do you have a kcm_kwin4_genericscripted.so (yes, "kwin**4**") at "/usr/lib/qt/plugins/kwin/effects/configs/"?

**Comment by faho** [comment]
Oh, the /usr/lib/qt/plugins part of that is one of the values of $QT_PLUGIN_PATH.

**Comment by MaxG87** [comment]
Yes, I used the latest git-version. The version from KWin-Script-Repository did not work at all and was very hard to remove. It's possible that I did not remove it entirely.
To answer the kcm_kwin stuff I'll paste some bash-output:

   /$ cd /
    /$ find -iname 'kcm_kwin[45]_*' 2> /dev/null 
    ./usr/lib/x86_64-linux-gnu/qt5/plugins/kwin/effects/configs/kcm_kwin4_genericscripted.so
    /$ echo $QT_PLUGIN_PATH 
    /usr/lib/x86_64-linux-gnu/qt5/plugins:/lib/kde5/plugins/

**Comment by faho** [comment]
That's certainly weird. Can you try reinstalling with `plasmapkg2`?

Anyway, the configuration interface shouldn't be necessary to use the script - does it _run_?

**Comment by MaxG87** [comment]
It was due to the manual copying. I removed the manually created folder and used plasmapk2. Since then it works like a charm. No I can check whether it is as good as awesome.

**Comment by faho** [comment]
>I can check whether it is as good as awesome.

Probably not. 

Anyway, nice you fixed your issue.

**Comment by MaxG87** [comment]
I am very sorry to reopen this, but it was not due to plasmapkg2 for me. I have a second PC which is almost exactly the same. The main difference is, that the second runs 32Bit Debian.

However, installing kwin-tiling using plasmapkg2 did NOT WORK since kwin-tiling was copied into

    ~/.kde/share/apps/kwin/scripts/kwin-script-tiling

It has to be at

    ~/.local/share/kwin/scripts/kwin-script-tiling

So the correct installation routine for me was

1. clone repository
2. run plasmapkg2
3. ensure, that the folder is in the right place

Just to be explicit: This is for Plasma 5.

**Comment by faho** [comment]
>~/.kde/share/apps/kwin/scripts/kwin-script-tiling

Are you sure you ran "plasmapkg**2**"? That's the directory for KWin4.

**Comment by MaxG87** [comment]
I'll prove that:

    history | grep plasma
    1068  sudo aptitude hold plasma-workspace plasma-desktop kde-workspace-bin 
    1070  sudo aptitude hold kde-plasma-desktop kde-standard task-kde-desktop 
    1316  sudo aptitude hold kde-standard kde-plasma-desktop plasma-desktop
    1318  sudo aptitude hold plasma-workspace
    1319  sudo aptitude unhold plasma-desktop
    1323  sudo aptitude hold plasma-desktop
    1327  sudo aptitude hold kde-standard kde-plasma-desktop plasma-desktop plasma-workspace kde-workspace
    1334  sudo aptitude hold ~nplasma ~nkde
    1391  sudo aptitude install plasma-desktop sddm -s
    1392  sudo apt-get install plasma-desktop sddm
    1411  psgrep plasma
    1412  /usr/bin/plasma --help
    1413  /usr/bin/plasmashell --help
    1422  cd ~/.config/plasma-workspace/env/
    1428  plasmashell 
    1429  psgrep plasma
    1430  psgrep plasmashell
    1431  rm .config/plasma-workspace/env/set_window_manager.sh 
    1753  plasmapkg2 –type kwinscript -i .
    1758  plasmapkg2 –type kwinscript -i .
    1763  plasmapkg2 –type kwinscript -i .
    2001  history | grep plasma

**Comment by faho** [comment]
>1753  plasmapkg2 –type kwinscript -i .

Okay, github's org formatting is off - that's supposed to be a `--type`, not "-type" (just like in #44).
