### ISSUE TITLE
kwin-tiling makes iceweasel+pentadactyl unusable

### ISSUE THREAD

**Issue by MaxG87** [faho/kwin-tiling#43]
After successfully installing kwin-tiling I discovered, that it makes my browser setup unusable. I use Iceweasel with the vim-mode plugin Pentadactyl. My OS is Debian/testing. All my software is from the usual repositories.

With unusable I mean that Iceweasel is

  * not loading open tabs
  * not responding to the usual keyboard instructions
  * not responding to mouse clicks

Since the severity itself may be low since Pentadactyl and kwin-tiling may be not seen together that often, it seems to be a good hint that there might be a bug hidden somewhere.

**Comment by faho** [comment]
Try resizing it - I'm pretty certain this is #6.

**Comment by MaxG87** [comment]
You're right. Sorry for the duplication.
