### ISSUE TITLE
Installation on Kubuntu 15.04 does not do anything

### ISSUE THREAD

**Issue by martin-ueding** [faho/kwin-tiling#44]
I just tried to install it on a fresh user on Kubuntu 15.04 with the instructions given. It will give the following:

```
pluginname:  "kwin-script-tiling"
-- Copying  "/home/tiling/.local/share/plasma/plasmoids/kwin-script-tiling/metadata.desktop" "/home/tiling/.local/share/kservices5/plasma-applet-kwin-script-tiling.desktop"
Could not register package as service (this is not necessarily fatal): "plasma-applet-kwin-script-tiling.desktop"
Successfully installed /home/tiling/kwin-tiling
```

When I try the `--list` command, it does not list your script. It is shown in the KDE Systemsettings, though. When I try to access the configuration, it will tell me that the script does not provide a configuration file in a default location.

Am I doing something wrong? How can I install this on Plasma 5 on Kubuntu 15.04?

**Comment by faho** [comment]
>plasma-applet-kwin-script-tiling.desktop

The error appears to be that it's trying to install it as a plasma applet, which it isn't.

It seems github's formatting has eaten a dash - the installation instructions should be

    plasmapkg2 --type kwinscript -i /path/to/script

Note that it's `--type` with a double-dash. Please try that and report back.

**Comment by martin-ueding** [comment]
It now works! Thanks!
