### ISSUE TITLE
Make screens independent

### ISSUE THREAD

**Issue by MaxG87** [faho/kwin-tiling#45]
Hi,
since awesome-wm and Plasma 5 don't play well together anymore, I'm looking for an alternative. I'm using kwin-tiling at home with one monitor and I really like it.

However, on multi-monitor setups it manages both screens like one big one. Thus, switching the virtual desktop of a laptop screen also switches the virtual desktop of the standalone screen. I really dislike this behaviour.

Thus, I have to questions:

  1. Is it possible to script independent screens into kwin?
  2. Would it be a desired feature of kwin?

Thanks for the great plugin btw.

**Comment by faho** [comment]
>Is it possible to script independent screens into kwin?

As a script, not without major hacking. The only approach I can see is to emulate it by switching all clients of the involved VDs - i.e. if you are switching from VD 2 to VD4 on monitor 1, you'd need to switch all clients on monitor 2 that are on VD4 to VD2 and vice versa. This doesn't seem like it would work well and would need a fair bit of code, especially making it work with tiling.

 >Would it be a desired feature of kwin?

If you mean kwin-tiling (this script) I'm afraid not. This is outside of the scope and, as I said above, very hackish and error-prone in addition to being a ton of work.

If you mean kwin proper, you'll have to ask Martin Gräßlin - the maintainer.

**Comment by MaxG87** [comment]
That sounds discouraging. Anyway, thank you very much.

**Comment by henri-nourel** [comment]
Hi, 
I am in the same situation as MaxG87, so the solution is to look at kwin

**Comment by MaxG87** [comment]
I tried to find an answer to this, but I don't like it.
Independent screens as described here would violate some norm and will therefor maybe be supported with Wayland but definitely not earlier.

https://bugs.kde.org/show_bug.cgi?id=107302

**Comment by faho** [comment]
Okay. Until the situation changes in KWin, I'm going to close this.
