### ISSUE TITLE
gVim and a couple other programs are transparent until a window resize

### ISSUE THREAD

**Issue by martin-ueding** [faho/kwin-tiling#46]
I am not sure how this relates to #9. Most times I open gVim or a couple other programs (just happened with Shutter), the tiling layout will make room for the new window. I can see the background image only until I resize the window or the other ones.

This is pretty annoying as I always have to do something like maximize and un-maximize with every gVim window that I use.

This is what it looks like:

![Screenshot of transparent window](http://chaos.stw-bonn.de/users/mu/uploads/2015-10-11/2.png)

You can see how the KSnapshot window is still visible even though it should be hidden while taking the screenshot. I guess that the gVim window there is not properly repainted.

**Comment by faho** [comment]
Run kwin (or `kwin_x11`) in a terminal, you'll see loads of ">Creating window pixmap failed: SOMETHING". 

This is #6, which in turn is waiting on https://bugs.kde.org/show_bug.cgi?id=341195.

Sorry.

**Comment by martin-ueding** [comment]
Thanks for the fast response! We will have to wait for the upstream bug, then.
