### ISSUE TITLE
[Request] Hotkey/Button to toggle on/off

### ISSUE THREAD

**Issue by xlegs** [faho/kwin-tiling#47]
There are already full on tiling WMs, but it would be cool if users could enable or disable tiling on-the-fly. It's ideal for people who want to try tiling without going all in.

**Comment by faho** [comment]
That's already included on a per-desktop basis ("Meta-Shift-F11" - where "Meta" is the windows key). Also there's a checkbox in the configuration to disable it by default.

Unfortunately, hotkeys are currently non-functional for qml-based scripts in Plasma 5's KWin.

**Comment by xlegs** [comment]
Ok. I'm on Plasma 5. I'm assuming it's a Frameworks thing? If so, how do I know when it's implemented?

**Comment by faho** [comment]
https://bugs.kde.org/show_bug.cgi?id=340225 - I believe you can add yourself to the CC list.
