### ISSUE TITLE
Multimonitor branch out of date

### ISSUE THREAD

**Issue by airways** [faho/kwin-tiling#48]
The multimonitor branch currently is very out of date, without changes from plasma5 branch, and probably many other things. Are there plans to update this branch or merge it's functionality into master?

Thanks, great script!

**Comment by faho** [comment]
I don't think there's anything in that branch that's still relevant. Multimonitor is supposed to work on master (i.e. P5), though I don't use it myself except for testing. If there's anything in particular that breaks on MM, please open an issue!
