### ISSUE TITLE
Multimonitor on Ubuntu 14.04 not working for me

### ISSUE THREAD

**Issue by airways** [faho/kwin-tiling#49]
I have installed Kubuntu packages via Tasksel on a machine that was originally Xubuntu. After switching to KDE, I installed the kwin-tiling script via the KDE script install dialog.

When I have an external monitor plugged in and set to primary, my secondary monitor (arranged below the primary) does not having tiling. The monitors appear to be part of a single desktop in the virtual desktop pager I have on my main panel.

**Comment by faho** [comment]
Can you start kwin in a console (`kwin_x11 --replace`)? Also, please try current git master (though I'll probably make a new release and upload it to kde-look.org soon, given that Plasma 4 is now EOL). Which KWin version is this?

**Comment by airways** [comment]
KDE is 4.13.3
KWin is 4.11.11

It seems that simply restarting KWin after already being logged on sort of got tiling to work in the non-primary monitor. However, I've noticed a lot of issues moving windows back and forth between monitors. They often snap to full screen on the new monitor and leave an empty space where they were on their previous monitor.
Attaching a log and some screenshots.

In snapshot5 I had moved a terminal from the lower right (which is the second screen) up to the main screen. Firefox went full screen suddely.
![snapshot5](https://cloud.githubusercontent.com/assets/64338/11688521/c3d5f8ea-9e52-11e5-8771-3c84de88da27.png)

I found the terminal under firefox, by resizing it down. Firefox seems to have lost tiling somehow.
![snapshot6](https://cloud.githubusercontent.com/assets/64338/11688520/c3d56100-9e52-11e5-93df-e22d32d9bab4.png)

[kwin.log.txt](https://github.com/faho/kwin-tiling/files/56916/kwin.log.txt)

**Comment by airways** [comment]
git master seems to not work at all, no windows have tiling under this version.
[kwin2.log.txt](https://github.com/faho/kwin-tiling/files/56935/kwin2.log.txt)

**Comment by faho** [comment]
>kwin(4083) KWin::DeclarativeScript::createComponent: Component failed to load:  (file:///home/iraway/.kde/share/apps/kwin/scripts/kwin-script-tiling/contents/ui/main.qml:21:1: module "QtQuick" version 2.0 is not installed
    import QtQuick 2.0;
    ^)

git master is now Plasma 5, so this won't work on KWin 4.11. I think there's not much you need to change - essentially revert 94bf9949327f2f1ea1d1331d3e31e30c8315b3ce.

I strongly suggest you update to KWin 5.

Anyway, I'll try to reproduce the multimonitor issues when I get access to another monitor.

**Comment by airways** [comment]
I would have to use some kind of backports ppa to get plasma 5. Not really excited about that since it seems likely to cause other problems. Is kwin-tiling no longer supported on 4.11x?

**Comment by airways** [comment]
I reverted that commit and reinstalled but it didn't change much.
[kwin3.log.txt](https://github.com/faho/kwin-tiling/files/56997/kwin3.log.txt)

**Comment by faho** [comment]
>Is kwin-tiling no longer supported on 4.11x?

Not really. I'm open to someone else working on it, but I myself no longer use it and hence can't really test. There's a plasma1 (sic!) branch, but I haven't kept up with backporting. Sorry!

**Comment by paulroemer** [comment]
Hey faho,

I jumped on the multiple monitor train and yes, it doesn't seems to work as expected.

kwin 5.5.5 and I am using kwin-tiling from master.

First of all, krunner is not visible anymore. 
Secondly, eclipse and other GTK apps behave strange as you can see here:
![screenshot_20160405](https://cloud.githubusercontent.com/assets/16225666/14272079/af566288-faff-11e5-8ef8-09d64e865ed1.png)

I can move them to the second monitor but they loose tiling and jump to the bottom of the screen.

Can you reproduce this?

Cheers,
  Paul

**Comment by paulroemer** [comment]
Then let me now how I can decrease the time you need to test the multi-monitor support ; )

**Comment by faho** [comment]
@paulroemer: Please test a88c2ff, which works for me.

**Comment by paulroemer** [comment]
Looks promising. If I find any bugs I will open another issue. Thanks a lot!
