### ISSUE TITLE
respect minimum/maximum size doesn't work.

### ISSUE THREAD

**Issue by Limdel** [faho/kwin-tiling#56]

**Comment by faho** [comment]
Works for me. You'll need to restart kwin for it to take effect, though (like for all our options).

**Comment by Limdel** [comment]
rebooted multiple times. both bugs are present. can't add class name and tiling doesn't respect minimum size.

**Comment by faho** [comment]
The class name thing was #55, which I just fixed, so you'll need to get the latest commit from git.

I believe I know what's going on with the min/max thing: The default in the config is false, while the default in the code is true. It seems kwin nowadays won't write the defaults out anymore (or rather it'll delete any setting that has been set to the default from the config file), so it'll set it to an explicit true or implicit true. Dunno why my first attempt succeeded.
