### ISSUE TITLE
Yakuake

### ISSUE THREAD

**Issue by paulroemer** [faho/kwin-tiling#58]
Another one:

Unfortunately, Yakuake (the Quake-styled console) gets tiled to. Can you confirm this?

Cheers,
  Paul

**Comment by faho** [comment]
Humm... I use yakuake pretty much once per minute and it's in the [default exclusion list](https://github.com/faho/kwin-tiling/blob/master/contents/config/main.xml#L10). Have you removed it from there?

**Comment by paulroemer** [comment]
Can you give me a hint where kwin logs print()/stdout statements?

**Comment by faho** [comment]
>Can you give me a hint where kwin logs print()/stdout statements?

For me it all ends up in ~/.xsession-errors. Or you could run `kwin_x11 --replace`

>krunner seems to affected, too.

That's another one that's in the default list. Can you do `xprop` and click on the affected clients? The "WM_CLASS(STRING) =" line is the interesting one, and should be '"yakuake", "yakuake"' and '"krunner", "krunner"', respectively. Also in ~/.config/kwinrc, there should be in the "[Script-kwin-script-tiling]" section either a "floaters" setting that includes both "yakuake" and "krunner" or no floaters setting at all (kwin doesn't save unchanged settings).

**Comment by paulroemer** [comment]
The problem was an empty floaters setting in the kwinrc. After removing it everything works as expected.

Thanks again!
