### ISSUE TITLE
JConsole, JProfiler

### ISSUE THREAD

**Issue by paulroemer** [faho/kwin-tiling#59]
Hi,

I'm faced with ugly rendering problems with Java AWT/Swing applications. 

![screenshot_20160221_121114](https://cloud.githubusercontent.com/assets/16225666/13202248/452e6884-d894-11e5-9629-83d346d88686.png)

I tried to add them

WM_CLASS(STRING) = "sun-awt-X11-XFramePeer", "sun-tools-jconsole-JConsole"

to the main configuration file but without success. Without tiling everything works as expected.

Can you check it?

Cheers,
  Paul

**Comment by faho** [comment]
This is most like just #6 (which is very annoying indeed) - have you tried resizing these windows (i.e. pressing alt+rightclick on that window or the konsole one)? That usually helps.

Also, I believe KWin now gives the script the windowclass in lowercase, so you might want to add it that way.

Where do I get these things to confirm? Neither the Arch repos nor the AUR seem to contain them.

**Comment by paulroemer** [comment]
12:58:18 paul@tuxbook:~> rpm -qf /usr/lib64/jvm/java-1.8.0-openjdk/bin/jconsole
java-1_8_0-openjdk-devel-1.8.0.72-6.1.x86_64

For Arch it's package jdk8-openjdk
https://www.archlinux.org/packages/extra/x86_64/jdk8-openjdk/

Maximizing the window helped. Changing the windowclass name to lower case not. 
```
        <entry name="floaters" type="StringList">
                  <label>The windows (by class) that should float</label>
                  <default>yakuake,plasma,plasma-desktop,krunner,plugin-container,klipper,Wine,sun-tools-jconsole-jconsole,sun-awt-x11-xframepeer</default>
        </entry>
```

**Comment by faho** [comment]
Oh, I already had it installed!

This is definitely #6 - like I said, resizing it (not maximizing, just resize-grabbing it and shaking it a bit) works.

If you don't want to have it tiled, the window class as the script sees it is "sun-tools-jconsole-jconsole", i.e. the lowercase version of the second entry in WM_CLASS.

**Comment by paulroemer** [comment]
Hmm... upstream bug is open since 2014...

Ok, I will workaround this.

Thanks!

**Comment by faho** [comment]
I'll close this as a duplicate.
