### ISSUE TITLE
kwin-tiling locks up clients (timing issue)

### ISSUE THREAD

**Issue by Keks-Dose** [faho/kwin-tiling#6]
openSuse 13.1, GNU Emacs 24.3.1 (x86_64-suse-linux-gnu, GTK+ Version 3.10.2) of 2013-12-03 on build22, KDE 4.11.3, Kernel 3.12.3

Installed kwin-tiling, activated and tried to have Emacs on one side and okular on the other side of the screen. But Emacs kind of freezes after every command. I can unlock it by klicking on the icon for changing the window size, but you can't work this way, of course.

So maybe you, Fabian, you can have a look into this. At the first moment I was really surprised to see your approach, but probably you are right to use just a script. 

Probably most people just wish to have two windows side by side, everything else won't be used much.

**Comment by faho** [comment]
As for emacs, I found a workaround:

Set `frame-resize-pixelwise` to non-nil, like so:

```
(if (display-graphic-p)
	(progn
	  (setq frame-resize-pixelwise t)))
```

**Comment by wd5gnr** [comment]
By the way. I unblacklisted the "wine" window class and did a rule with a substring match of <space>wine (that's a real space not the word <space>) and applied that same fix and now several Wine programs I use tile properly and behave. In addition, the same fix works for Arduino (with a rule pointing at its window class, of course).

**Comment by gagbo** [comment]
These workaround might be worth to add in the README (in the troubleshooting section with the "getting settings menu to appear in ksettings"). I just used the emacs trick (which works on 26.1 on Fedora Rawhide/30 ), but it might be easier to find this on the README
