### ISSUE TITLE
multiple monitors not supported?

### ISSUE THREAD

**Issue by paulroemer** [faho/kwin-tiling#60]
Hi faho,

I recently added a comment to another issue. And because I'm a little spoiled of your fast response time of the last issue I added, I want to be on the safe side that you get notified.

Here is the link to my comment:
https://github.com/faho/kwin-tiling/issues/49#issuecomment-205652512

Cheers,
  Paul

**Comment by faho** [comment]
Yeah, I had seen that one, I just didn't get to testing multi-monitor.

Let's track there.
