### ISSUE TITLE
How to exclude YaKuake and Krunner?

### ISSUE THREAD

**Issue by v3ss0n** [faho/kwin-tiling#61]
can't exclude from the setting.?

**Comment by v3ss0n** [comment]
Krunner , Yakuake and start menu , thoses are floats right? they should be excluded by default.

**Comment by faho** [comment]
They [are](https://github.com/faho/kwin-tiling/blob/master/contents/config/main.xml#L10) excluded by default!

Otherwise, you should add "krunner", "yakuake" and "plasmashell" to your exclusion list (see the "WM_CLASS" output when you run `xprop` and then click that window).

**Comment by v3ss0n** [comment]
there is no interface to setting them.

**Comment by faho** [comment]
@v3ss0n: That's most likely https://bugs.kde.org/show_bug.cgi?id=347176. What you need to do (and what I haven't figure out how to generally) is adjust the "X-KDE-LIBRARY" path to the correct path to kcm_kwin4_genericscripted.so (without the ".so" part, I think) in metadata.desktop. This should be `qtpaths --plugin-dir`/kwin/effects/configs/.

Then you'll be able to go to system settings -> window management -> kwin scripts and get the config UI.

Sorry for the inconvenience.

**Comment by v3ss0n** [comment]
ahh , i got to try that. Currently i end up modifying the kwin-tiling code and hardcoded the list of floats.

**Comment by faho** [comment]
Closing this in favor of #64, that one has a bit more discussion.
