### ISSUE TITLE
Kwin crashes after 5.7 update

### ISSUE THREAD

**Issue by v3ss0n** [faho/kwin-tiling#63]
Update to Kwin 5.7 with Kde 5.23.0 and having random kwin 100% CPU / restart problems.
It happens while switching between multiple windows.

**Comment by faho** [comment]
First of all, the obvious: Does this happen without the script?

Then, a few more questions:

- Which options are you using?

- Which graphics drivers?

- What do you mean "switching between multiple windows"? Can you be more specific?

**Comment by v3ss0n** [comment]
i use default settings , as i cannot configure from config at all. All i did is system upgrade and it starting to have freezes. I will test by disabling too.
Intel graphic drivers. Optimus dosen't work at all so diabled nvidia card.
When i click between different tiled windows (not with al-tab)

**Comment by piotr-dobrogost** [comment]
There are some problems with KDE Plasma 5.7 and KDE Frameworks 5.23.0; for instance system tray doesn't show up. Try installing KDE Frameworks 5.24

**Comment by v3ss0n** [comment]
Sabayon distro do not have 5.24 yet , so i gotta wait.
Yeah it happens sometimes for me too.  And sometimes all the tiled windows are flickering like LSD effect.

**Comment by v3ss0n** [comment]
Latest KDE Frameworks fixed this problem.
