### ISSUE TITLE
What is the status of this script for KDE 5.7 ?

### ISSUE THREAD

**Issue by IbnSaeed** [faho/kwin-tiling#65]
Hello
What is the status of this script for KDE 5.7 ?

What things work and what are broken ?

Is it safe to use it  with KDE 5.7.3 ?

**Comment by faho** [comment]
It's safe to use, but the hotkeys and configuration menu don't work. The former is because the script API has a bug, the latter because the widget this uses has been removed.

**Comment by Teyras** [comment]
Is there any chance you'll fix it soon, or post some hints so that I can help? I would really like to try this out, but tiling doesn't make much sense without hotkeys.

**Comment by faho** [comment]
The script API bug is up to the kwin maintainers. I reported it as https://bugs.kde.org/show_bug.cgi?id=340225, but the kwin people have a lot on their plates and haven't gotten to it yet.

To make the config menu work again, I'd need to figure out which widget to replace the KEditListWidget with. So far I haven't found one.

**Comment by piotr-dobrogost** [comment]
> I'd need to figure out which widget to replace the KEditListWidget with.

How about using _flat_ (one level) TreeView?

**Comment by faho** [comment]
>How about using flat (one level) TreeView?

We need something that we can add stuff to without any additional code. I don't think TreeView offers that.

**Comment by faho** [comment]
Okay, I just looked again. I can't find a widget that has a nice "add" button so you can add one item, there's no matching pre-made signals/slots to make our own. So the best is one of the free-form text entry things. Of those, we cannot use the ones with html - since I have no inclination to parse that in the script. So that leaves QPlaintextEdit and splitting on ",".

Which is annoying.

**Comment by v3ss0n** [comment]
Sadly , KDE's main developer Discouraged the api change necessary for the hotkeys and ignored the bug report.

**Comment by faho** [comment]
@v3ss0n: That kinda fits better in #30.

The question at hand has been answered, so I'm closing this.

**Comment by v3ss0n** [comment]
thanks.
