### ISSUE TITLE
[Bug?] Shortcuts

### ISSUE THREAD

**Issue by stefanivic** [faho/kwin-tiling#69]
Hello,
Just noticed the commit for re-enabled keyboard shortcuts. I cloned the repo and reinstalled the script but for some reason they still don't work. 

Plasma 5 : 5.8.3
kwin-tiling : 1.7.0

**Comment by faho** [comment]
Which shortcuts have you tried? Can you confirm that you installed that actual commit? 1.7.0 doesn't have it (the tag called 1.7.0, the script will still report 1.7.0 as the version).

Do you have the shortcuts listed in systemsettings -> global shortcuts?

**Comment by stefanivic** [comment]
I tried almost all of them. I will try to remove the script fully and install it again. 
Also, no i do not have any shortcuts related to kwin-tiling.

**Comment by faho** [comment]
> Also, no i do not have any shortcuts related to kwin-tiling. 

Well, if you don't have e.g. "Toggle Floating" in the list, then of course it's not gonna work if you press the keys for "Toggle Floating".

Please see if you have actually installed the correct version - there should be "KWin.registerShortcut" calls in ~/.local/share/kwin/scripts/kwin-script-tiling/contents/code/tilingmanager.js.

**Comment by stefanivic** [comment]
Yeah, after i removed the script, cloned again and installed it works fine now. Thanks and sorry for the trouble. Should have done it from the start. Great work on the script!
