### ISSUE TITLE
Clean up mixed indentation

### ISSUE THREAD

**Issue by ohjames** [faho/kwin-tiling#70]
I wanted to submit a few PRs but the code is really hard to work with given the mixture of tabs and spaces for indentation. Can you add an `.editorconfig` file to insist your chosen style and apply it to existing files?

**Comment by faho** [comment]
Yes, I probably should have done that before. The problem was that I switched my editor's config because of other projects I work on, only it doesn't seem to apply to already indented lines. So I've been doing the stuff to reindent lines, but it hasn't had any effect.

This should now be fixed.
