### ISSUE TITLE
What keyboard shortcuts are supported and how to change them?

### ISSUE THREAD

**Issue by piotr-dobrogost** [faho/kwin-tiling#71]
I can't find information on what keyboard shortcuts are supported.
Does tiling register global shortcuts so that one could edit them using "Global Shortcuts" system settings module?

**Comment by faho** [comment]
>Does tiling register global shortcuts so that one could edit them using "Global Shortcuts" system settings module?

Yes.

The script offers the following shortcuts:

- Next Tiling Layout
- Previous Tiling Layout
- Toggle Floating
- Toggle Border for all
- Move Window Left
- Move Window Righ,
- Move Window Up
- Move Window Down
- Toggle Tiling
- Tile now
- Swap Window With Master
- Resize Active Window To The Left
- Resize Active Window To The Right
- Resize Active Window To The Top
- Resize Active Window To The Bottom
- Increase Number Of Masters (where "master" is a layout's idea of the "main window". In the default "halflayout" that's the window on the left. If you add one more, then the left half will be divided into two)
- Decrease Number Of Masters

I actually wanted these to all start with "TILING", but I changed the wrong argument, and changing it now wouldn't remove the old ones.

Also, none of these names are localized because I don't know how.

**Comment by piotr-dobrogost** [comment]
> I actually wanted these to all start with "TILING", but I changed the wrong argument, and changing it now wouldn't remove the old ones.

Even better if all these shortcuts could have been placed under separate entry in _Global Keyboard Shorctucts_.

Meanwhile I wouldn't bother with leftover ones and would suggest to prefix them with TILING as you originally intended.

**Comment by jluttine** [comment]
Where can I find these shortcut definitions? I looked under System Settings -> Shortcuts and there "Standard Shortcuts", "Global Shortcuts", "Web Shortcuts" and "Custom Shortcuts" but couldn't find those listed shortcuts. I'm using KDE Plasma version 5.8.5 under NixOS.

**Comment by piotr-dobrogost** [comment]
Wow, NixOS!

Under *Global Shortcuts* choose *KWin* component.

**Comment by jluttine** [comment]
Nope, none of those appears to be there. Just lots of other standard KWin shortcuts. I both searched and manually read the list. Any ideas what could be wrong? I hope I have the correct KWin script installed: Tiling Extension version 1.7.0 by Fabian Hombord.

**Comment by faho** [comment]
>Tiling Extension version 1.7.0 by Fabian Hombord.

@jluttine: That's an old version that (I think) had the shortcuts disabled. You'll need to upgrade.

Also my last name is spelled with a "g" - like the creatures from Star Trek. I am the Homborg, resistance is futile! 😄

**Comment by jluttine** [comment]
So the version available from System Settings -> Window Management -> KWin Scripts -> Get New Script -> kwin-tiling-plasma5 is old? I expected that to be the correct way to install the latest stable release as it's the only channel offered by KDE. Anyway, I now uninstalled that and followed the instructions on readme using git clone etc. However, I believe KWin is still using the old version or nothing. Also, the version 1.7.0 is still listed in KWin Scripts.. I'm really confused. I don't find any sign that the script installed with readme instructions is actually installed. How can I confirm that and also check the version? FYI, I'm new to KDE.

**Comment by jluttine** [comment]
Also, how do I uninstall the script? Readme contains only installation instructions..

**Comment by piotr-dobrogost** [comment]
@eddhannay 
From https://github.com/faho/kwin-tiling/issues/71#issuecomment-269766261
> I'm using KDE Plasma version 5.8.5 under NixOS.

**Comment by eddhannay** [comment]
My mistake - New to kde, I found this issue trying to solve the same issue, discovered I was running 5.8.2 and hadn't realised that the kwin version was tied to the Plasma version.

**Comment by piotr-dobrogost** [comment]
No problem. Welcome to KDE!

**Comment by faho** [comment]
>However, I believe KWin is still using the old version or nothing

Do the shortcuts still not work? Did you restart kwin after you updated?

>Also, how do I uninstall the script? Readme contains only installation instructions..

Actually you should be able to `plasmapkg2 -r kwin-script-tiling`, but it seems to currently be borked for me for kwinscripts (though it's also possible some of the fiddling I did during dev caused this). 

If it doesn't work for you either, you can disable it in systemsettings and remove the directory from ~/.local/share/kwin/scripts. I _think_ then `kbuildsycoca5` should pick up that it's been removed.

>Also, the version 1.7.0 is still listed in KWin Scripts

I haven't bumped the version yet. I should probably do that, and make a new release.

>And sorry for getting off-topic. Perhaps I should open a separate issue or ask using some other forum?

If you have any further questions, please open a separate issue.

**Comment by haadr** [comment]
Just thought I'd chime in.

I'm running plasmashell 5.8.4 (debian testing) and I have the same problem of it not displaying the shortcuts under Global Shortcuts/Kwin. Also, removing the plugin via plasmapkg2 -r kwin-script-tiling doesn't work (as expected?) and removing the directory and logging out and in again doesn't help either, it's still displayed in under KWin Scripts. 

Otherwise it seems to be active as expected when activated, but that doesn't help when I can't see the shortcuts to use it :D

**Comment by faho** [comment]
The question has been answered.

**Comment by m-scr** [comment]
Sorry for necrobumping this, but I had the same problem (no shortcuts showing in Global Keyboard Shortcuts -> KWin) on NixOS, and I managed to find a workaround.

I first executed the commands:
```
mkdir -p ~/.local/share/kservices5
ln -s ~/.local/share/kwin/scripts/kwin-script-tiling/metadata.desktop ~/.local/share/kservices5/kwin-script-tiling.desktop
```

[as suggested here](https://github.com/faho/kwin-tiling/issues/79#issuecomment-311465357). I then updated the tiling extension (`plasmapkg2 --type kwinscript -u .`), disabled it in Kwin Scripts, and re-enabled it. The shortcuts appeared!

I don't know how many users might have been affected by this, it could be worth mentioning in the _troubleshooting_ section of the README.

**Comment by florianjacob** [comment]
@m-scr NixOS 18.09 as well, kwin 5.13.4, recently installed kwin-tiling via
```
git clone https://github.com/faho/kwin-tiling.git
cd kwin-tiling/
plasmapkg2 --type kwinscript -i .
```

and for me, the shortcuts appeared like expected. Did you install via Get New Script or via plasmapkg2 and the git repo?

**Comment by m-scr** [comment]
@florianjacob I installed via plasmapkg2, but I was on the nixos-unstable channel. It appears to work on the old stable 18.09, I haven't tested 19.03 yet.
