### ISSUE TITLE
Tiled windows should always be set to "unmaximized" state

### ISSUE THREAD

**Issue by piotr-dobrogost** [faho/kwin-tiling#72]
When a window is restored (for example at first window is minimized and then its entry on the taskbar is clicked) it maintains its maximized/unmaximized state. As a _Maximized Window_ KWin shortcut does in fact toggles between maximized and unmaximazed states this leads to having to type shortcut once (unmaximized ➟ maximized) or twice (maximized ➟ unmaximized ➟ maximized) on a tiled window to maximize it. To avoid this and to make behavior consistent when a window is being tiled it should always be set to unmaximized so that applying _Maximize Window_ shortcut once would always maximize it the first time it's used. The only exception could be if a tiled window is the only one on a given screen; in this case it could be set to maximized (which is current behavior).

**Comment by faho** [comment]
You know, this and #73 are so related that I think we can keep it in one issue. Let's close this one since I already commented there.

**Comment by piotr-dobrogost** [comment]
> You know, this and #73 are so related that I think we can keep it in one issue. Let's close this one since I already commented there.

This is related but different than issue #73 and should stay open. According to Martin Gräßlin (today on #kwin channel) the fact that a window which is not _physically_ maximized is in the maximized state is a bug in KWin and it was not raised in the past. Thus the issue described here is an upstream bug in KWin. Please note that when it's fixed the question stated in issue #73 will still be valid which clearly shows these two problems are different.
