### ISSUE TITLE
Yakuake tiling

### ISSUE THREAD

**Issue by lcronos** [faho/kwin-tiling#77]
Hi I was looking through some of the issues on here and it says that yakuake should be excluded from the tiling process, however yakuake is being tiled anyway.  The issue that mentioned yakuake also mentioned a .js file, but when I looked at it, it appears to have changed since then.  Any suggestions?

**Comment by faho** [comment]
Yakuake is in the default exclusion list. Prior to e409fb7ad40b8850fa38a1a84d2cd33d21cd5a4d, this list was just the default for this configuration setting. So if you set the setting to empty, it would be tiled. And it seems to have been possible that opening the configuration menu caused this setting to be set to empty, so this happened a lot more than I wanted, and with less blame on the user.

So, for you, the solution is to upgrade to after that commit. You could also just use current git master, which conveniently is also 2.0.0 and should be available via GHNS (the "get new scripts" thing).

Do note that you want https://store.kde.org/content/show.php/Tiling?content=161151 (the thing called "Tiling"), and not https://store.kde.org/p/1154196/ (the thing called "kwin-tiling-plasma5"), which isn't maintained by me, hasn't been updated in a while and which uses my avatar as the icon.

**Comment by lcronos** [comment]
Hmm, I tried completely removing the tiling script (originally installed it through kde's settings) but it's still there.  I double checked that ~/.local/share/kwin/scripts/ was empty, but for some reason, even after a logout it still shows up under settings, and I can access its settings.  The git version installed despite this, but I don't know if I'm actually using the git version.

**Comment by faho** [comment]
Yeah, there's a bunch wrong with the plasmapkg system when it comes to kwin scripts.

Anyway, yakuake's working now, so that's nice.
