### ISSUE TITLE
Setting the width of "Resize Active Window To ..." in the configuration

### ISSUE THREAD

**Issue by TheIdealis** [faho/kwin-tiling#81]
It would be nice if one could specify the width of the "Resize Active Window To ..."-Shortcut in the configuration. It is hard coded to 10px and resizing the windows with the shortcut takes some time.

**Comment by faho** [comment]
I've thought about this as well, but I think the better solution would be to use a fraction of the resolution. I.e. "Resize to the left" would resize it by width / 20, "Resize to the top" would use height / 20.

Using configurable pixel values seems like a cop-out from the "not satisfied? configure it" school of design.

**Comment by faho** [comment]
I've just committed 67c1739, which just uses 1/20 of the applicable desktop (the "clientArea") dimension. That seems a bit nicer and should also automatically work for e.g. a 4K screen connected to a 1080p laptop.
