### ISSUE TITLE
Gvim "ghost" window

### ISSUE THREAD

**Issue by DaBlitzStein** [faho/kwin-tiling#83]
Hello,

With last version neon kde.

If you execute gvim with tile kwin script activated it appears as invisible window.

It happens with gvim-gtk/gnome all versions and gvim-adawaita.

Similar issue with terminator terminal.

- Tried the option for no window size. Nothing happens.
- If resize, the window shows.

**Comment by faho** [comment]
That's #6, which is waiting on work in KWin upstream.
