### ISSUE TITLE
after kwin --replace script stops working

### ISSUE THREAD

**Issue by ilkerhk** [faho/kwin-tiling#90]
Is there a way to restart the script after running kwin --replace ? 
This happens in plasma version 5.10 and 5.11

thanks...

**Comment by faho** [comment]
Oooh... This was [kwin bug 340125](https://bugs.kde.org/show_bug.cgi?id=340125), but it has been fixed in 5.8.4 and I completely forgot about it!

**Comment by ilkerhk** [comment]
Do you mean it is fixed so it supposed to work in 5.10 and 5.11? 
I am experiencing this on freshly installed kubuntu with plasma 5.10. 
I realized that kwin-tiling script is actually continues working,  but it can't see the windows which exists before kwin --replace. 
For example, if I open new windows (or restart the existing ones) those are tiled...

best...

**Comment by faho** [comment]
>Do you mean it is fixed so it supposed to work in 5.10 and 5.11?

No. What I mean is this was broken in KWin < 5.8.4, so I had to remove some code from the script. I then forgot about it and reenabled it in commit 2f4b9c8.

So when you install the script from git, it'll work. I'll see about making a new release so it'll work from GHNS (the script menu in systemsettings) as well.

**Comment by ilkerhk** [comment]
Working great now. Thanks...
