### ISSUE TITLE
installation on OpenSuse 42.3

### ISSUE THREAD

**Issue by githubkusi** [faho/kwin-tiling#93]
Using KDE Plasma 5.8.7 / KF 5.32, the following steps are needed for installation

* create directory  ~/.local/share/kservicetypes5
* copy metadata.desktop this repo to ~/.local/share/kservicetypes5/kwin-script.desktop
* in the cloned repo working directory: plasmapkg2 --type kwinscript -i .
* in kwin-script.desktop: replace Type=Service with Type=ServiceType
* enable plugin "Tiling Extension" in Settings/KWin Scripts

after that, everything works as expected

**Comment by faho** [comment]
None of that should be necessary. This is an upstream issue, and should be fixed there (and maybe it already is?).
