### ISSUE TITLE
pop-ups from Panel are includet in tiling too

### ISSUE THREAD

**Issue by rkunschke** [faho/kwin-tiling#97]
Whenn tiling is enabled the popUps from the Panel (VolumeControl, Clock ...) are included in the Tiling too. Can I exclude the with a Windowclass?

**Comment by faho** [comment]
>Can I exclude the with a Windowclass?

Essentially not - "class" is a bit of a misnomer here. What is used there is mostly the name of the application - vlc uses "vlc", firefox uses "Firefox", and the plasma popups use "plasmashell".

What you want is the window "type". However, the script already excludes all that aren't "normal window". However, the script already blacklists all things that aren't "normal windows" (which includes the dock itself), and the window class "plasmashell" - which includes these popups and such.

So my best guess is that you're running either an ancient version of the script (<2.0, which is the newest on kde-look.org), an ancient version of kwin, or kwin_wayland, which the script currently cannot support (wayland clients simply aren't exposed to it).

**Comment by rkunschke** [comment]
The Problem was that my panel was latte-dock. I excluded it but it makes no difference.
I use it with plasma-panel now

**Comment by faho** [comment]
>The Problem was that my panel was latte-dock.

Yup, that doesn't set the window type correctly - they're opened as "normal" windows, which for us means we tile them.

>I excluded it but it makes no difference.

You need the _second_ thing that `xprop` says in "WM_CLASS(STRING)". For latte-dock, that means `lattedock`. I've just tested it, and that works.

Anyway, this is really an issue in latte-dock.
